name: ScaniT
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # to allow the usge of writing/reading from user device storage.
  shared_preferences: ^0.5.6+3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # to create the icon of the application
  flutter_launcher_icons: ^0.7.4
  # to allow the usage of providers <3
  provider: ^4.0.4
  # to manipulate the DateTime format.
  intl: ^0.16.1
  # to allow the usage of dataBases
  http: ^0.12.0+4
  # to allow the usage of 'Scalable Vector Graphics' image format
  flutter_svg: ^0.17.4

flutter_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Merienda_One
      fonts:
        - asset: assets/fonts/Merienda_One/MeriendaOne-Regular.ttf
          weight: 400

    - family: Harmattan
      fonts:
        - asset: assets/fonts/Harmattan/Harmattan-Regular.ttf
          weight: 400

    - family: Monda
      fonts:
        - asset: assets/fonts/Monda/Monda-Regular.ttf
          weight: 400
        - asset: assets/fonts/Monda/Monda-Bold.ttf
          weight: 700

    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800

    - family: Amaranth
      fonts:
        - asset: assets/fonts/Amaranth/Amaranth-Regular.ttf
          weight: 400
        - asset: assets/fonts/Amaranth/Amaranth-Bold.ttf
          weight: 700

    - family: Architects_Daughter
      fonts:
        - asset: assets/fonts/Architects_Daughter/ArchitectsDaughter-Regular.ttf
          weight: 400

    - family: Baloo
      fonts:
        - asset: assets/fonts/Baloo/Baloo-Regular.ttf
          weight: 400

    - family: Baloo_2
      fonts:
        - asset: assets/fonts/Baloo_2/Baloo2-Regular.ttf
          weight: 400
        - asset: assets/fonts/Baloo_2/Baloo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Baloo_2/Baloo2-ExtraBold.ttf
          weight: 800

    - family: Basic
      fonts:
        - asset: assets/fonts/Basic/Basic-Regular.ttf
          weight: 400

    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf
          weight: 400

    - family: Monoton
      fonts:
        - asset: assets/fonts/Monoton/Monoton-Regular.ttf
          weight: 400

    - family: Press_Start_2P
      fonts:
        - asset: assets/fonts/Press_Start_2P/PressStart2P-Regular.ttf
          weight: 400

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway/Raleway-ExtraBold.ttf
          weight: 800

    - family: Reem_Kufi
      fonts:
        - asset: assets/fonts/Reem_Kufi/ReemKufi-Regular.ttf
          weight: 400

    - family: Rochester
      fonts:
        - asset: assets/fonts/Rochester/Rochester-Regular.ttf
          weight: 400

    - family: Saira_Semi_Condensed
      fonts:
        - asset: assets/fonts/Saira_Semi_Condensed/SairaSemiCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/Saira_Semi_Condensed/SairaSemiCondensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/Saira_Semi_Condensed/SairaSemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/Saira_Semi_Condensed/SairaSemiCondensed-ExtraBold.ttf
          weight: 800
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
